# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20, verbose_name='Серия')),
                ('rate', models.FloatField(default=0, verbose_name='Ставка')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Branch', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'locomotive',
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(verbose_name='Значение')),
                ('year', models.DateField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Год')),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Locomotive', verbose_name='Локомотив')),
            ],
            options={
                'verbose_name': 'Пробег',
                'verbose_name_plural': 'Пробег',
                'db_table': 'mileage',
            },
        ),
    ]
