# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 10:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locomotive',
            options={'verbose_name': 'Локомотив', 'verbose_name_plural': 'Локомотивы'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('amursky', 'Амурский'), ('east_siberian', 'Восточно-Сибирский'), ('far_eastern', 'Дальневосточный'), ('west_siberian', 'Западно-Сибирский'), ('western', 'Западный'), ('moscow', 'Московский'), ('northern', 'Северный'), ('north_western', 'Северо-Западный'), ('north_caucasian', 'Северо-Кавказский'), ('southern', 'Южный')], max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Год'),
        ),
    ]
